name: tunes-test
services:
  api:
    build:
      context: ./api
      dockerfile: ../build/api/Dockerfile
      target: test
    environment:
      - DATABASE_URL=postgres://test:password@db:5432/tunes?sslmode=disable
      - SECRET_TOKEN=testsecret
      - AUTH_DATABASE_URL=mongodb://test:password@auth-db:27017/auth?&authSource=admin
    depends_on:
      db:
        condition: service_healthy
      auth-db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      - POSTGRES_DB=tunes
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U test -d tunes
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 5s

  auth-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
    command: --quiet
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 5s
